using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.CartridgeLoader.Cartridges;

[GenerateTypedNameReferences]
public sealed partial class FineIssuanceUiFragment : BoxContainer
{
    private readonly NewFinePopup _newFinePopup;

    public Action<string, uint, string>? OnPrintPressed;

    public FineIssuanceUiFragment()
    {
        RobustXamlLoader.Load(this);

        _newFinePopup = new();
        SetupEventHandlers();
    }

    private void SetupEventHandlers()
    {
        _newFinePopup.OnFineIssued += (name, amount, crime) =>
        {
            OnPrintPressed?.Invoke(name, amount, crime);
        };

        NewFineButton.OnPressed += _ =>
        {
            _newFinePopup.ClearInputs();
            _newFinePopup.OpenCentered();
        };
    }
    
    public void UpdateState(List<string> citations)
    {
        MessageContainer.RemoveAllChildren();

        foreach (var citation in citations)
        {
        }
    }
}
